# netlify.toml

[build]
  # Derleme komutumuz ve yayınlama dizinimiz aynı kalıyor.
  command = "npm run build"
  publish = "dist"

# Sunucusuz fonksiyonlarımızı bu bölümde tanımlıyoruz.
[functions]
  # Fonksiyonlarımızı barındıracak klasörün adı.
  directory = "netlify/functions"
